import * as vscode from 'vscode'
import * as fs from 'fs'
import * as path from 'path'
import { Logger } from '../../logging/logger'
import { SettingsManager } from '../../config/settingsManager'
import { SecretService } from '../../secrets/secretService'
import { findOrCreateApisDir } from '../../utils/fs'
import { request } from '../../generation/runtime/clientProvider'

function parseInput(input: string): { projectId?: string; catId?: string; id?: string } {
  const mSpace = input.trim()
  if (/^\d+$/.test(mSpace)) return { projectId: mSpace }
  const pairs = mSpace.split(/[,\s]+/).map(x => x.trim()).filter(Boolean)
  const out: any = {}
  for (const p of pairs) {
    const m = p.match(/^(projectId|catId|id)[:=](.+)$/i)
    if (m) out[m[1]] = m[2]
  }
  return out
}

export function registerGenerateFromIds(context: vscode.ExtensionContext, deps: { logger: Logger; settings: SettingsManager; secrets: SecretService }) {
  return vscode.commands.registerCommand('apiforge.generateFromIds', async (uri?: vscode.Uri) => {
    const input = await vscode.window.showInputBox({ prompt: '输入 ProjectId/catId/id（例如：123 或 projectId=123,catId=45 或 id=678）' })
    if (!input) return
    const { projectId, catId, id } = parseInput(input)
    if (!projectId && !catId && !id) { vscode.window.showWarningMessage('未识别任何参数'); return }
    const cfg = deps.settings.getConfig()
    const yapiSources = (cfg.sources || []).filter(s => s.type === 'yapi')
    if (yapiSources.length === 0) { vscode.window.showErrorMessage('未配置 YApi 数据源'); return }
    let source = yapiSources[0]
    if (yapiSources.length > 1) {
      const pick = await vscode.window.showQuickPick(yapiSources.map((s: any) => s.sourceName), { placeHolder: '选择 YApi 数据源' })
      source = yapiSources.find((s: any) => s.sourceName === pick) || source
    }
    const folder = vscode.workspace.workspaceFolders?.[0]
    if (!folder) { vscode.window.showErrorMessage('未找到工作区'); return }
    const apisDir = findOrCreateApisDir(folder.uri.fsPath)
    const dest = path.join(apisDir, `${source.sourceName || 'yapi'}_${Date.now()}.ts`)
    const header = `// generated by ApiForge\n`
    const scope = id ? 'id' : (catId ? 'catId' : 'projectId')
    const scopeVal = id || catId || projectId
    const content = `${header}export async function fetch_${scope}_${scopeVal}() {\n  return ${JSON.stringify({ source: source.sourceName, scope, scopeVal })}\n}\n`
    fs.writeFileSync(dest, content, 'utf8')
    deps.logger.info(`已生成到 ${dest}`)
    vscode.window.showInformationMessage(`已生成到 ${dest}`)
  })
}